const DATA = {
  capitulos: [
    { titulo: "O começo de nós", subtitulo: "Toda grande história tem um instante em que tudo muda." },
    { titulo: "Nossa linha do tempo", subtitulo: "Alguns dias passam. Outros ficam morando na gente." },
    { titulo: "Nossos momentos", subtitulo: "Um pequeno álbum de tudo o que já fomos juntos." },
    { titulo: "Você lembra de nós?", subtitulo: "Sem competição: só uma volta carinhosa pela nossa história." },
    { titulo: "E se a gente pudesse…", subtitulo: "Escolhas pequenas, respostas cheias de significado." },
    { titulo: "Coisas que amo em você", subtitulo: "Vinte detalhes. E ainda assim, não caberia tudo." },
    { titulo: "Uma carta para guardar", subtitulo: "Algumas palavras merecem ser abertas devagar." },
    { titulo: "Os próximos capítulos", subtitulo: "O futuro não precisa de roteiro para ser bonito." },
    { titulo: "Uma cápsula do tempo", subtitulo: "Uma mensagem esperando pelo momento certo." },
    { titulo: "E ainda é só o começo", subtitulo: "O capítulo mais bonito é aquele que ainda vamos escrever." },
  ],
  momentos: [
    { data: "[DATA]", titulo: "O primeiro encontro", descricao: "Foi ali, entre a expectativa e o sorriso, que uma lembrança começou a nascer.", frase: "Eu ainda não sabia o tamanho daquela história." , icone: "✦" },
    { data: "[DATA]", titulo: "A conversa que ficou", descricao: "Daquelas conversas que fazem o tempo passar sem pedir licença.", frase: "Eu queria que a noite tivesse mais algumas horas.", icone: "☾" },
    { data: "[DATA]", titulo: "O começo do namoro", descricao: "O dia em que deixamos de imaginar e começamos a chamar de nosso.", frase: "Meu sim favorito continua sendo você.", icone: "♥" },
    { data: "[DATA]", titulo: "Nossa primeira aventura", descricao: "Um lugar novo, uma companhia conhecida e a sensação de que qualquer caminho podia ser bom.", frase: "Com você, até o caminho vira destino.", icone: "↗" },
    { data: "[DATA]", titulo: "A risada sem fim", descricao: "Aquele momento completamente nosso que fica melhor toda vez que lembramos.", frase: "Ainda rio quando penso nisso.", icone: "〰" },
    { data: "[DATA]", titulo: "Um dia simples", descricao: "Nada extraordinário aconteceu. E talvez por isso tenha sido tão especial.", frase: "O comum fica extraordinário ao seu lado.", icone: "☼" },
    { data: "[DATA]", titulo: "Um abraço necessário", descricao: "Às vezes, não era preciso resolver o mundo. Bastava encontrar o seu abraço.", frase: "Meu lugar preferido sempre foi perto de você.", icone: "♡" },
    { data: "[DATA]", titulo: "Uma conquista nossa", descricao: "Um daqueles momentos em que celebrar junto fez tudo ficar maior.", frase: "A sua alegria também é minha.", icone: "✧" },
    { data: "[DATA]", titulo: "Um plano improvisado", descricao: "A melhor parte foi não saber exatamente como o dia terminaria.", frase: "Adoro descobrir o mundo com você.", icone: "⌁" },
    { data: "[DATA]", titulo: "Dois anos de nós", descricao: "Uma coleção de dias, gestos e escolhas que continuam fazendo sentido.", frase: "E ainda temos tantas páginas em branco.", icone: "∞" },
  ],
  fotos: [
    { arquivo: "assets/fotos/WhatsApp-Image-2026-09-29-at-20.37.06-_1_-Copia.png", legenda: "Um momento nosso para guardar." },
    { arquivo: "assets/fotos/WhatsApp-Image-2026-09-29-at-20.37.06.png", legenda: "Mais uma lembrança que é só nossa." },
    { arquivo: "assets/fotos/WhatsApp-Image-2026-09-29-at-20.37.07.png", legenda: "Um instante especial ao seu lado." },
    { arquivo: "assets/fotos/WhatsApp-Image-2026-09-29-at-20.37.10.png", legenda: "Uma história feita de pequenos momentos." },
    { arquivo: "assets/fotos/WhatsApp-Image-2026-09-29-at-20.37.15.png", legenda: "Que bom viver essas memórias com você." },
  ],
  musicas: [
    { titulo: "Nossa música" },
  ],
  perguntas: [
    { texto: "Qual foi o nosso primeiro encontro?", opcoes: ["[NOSSO PRIMEIRO ENCONTRO]", "Um passeio surpresa", "Um almoço em família"], correta: 0 },
    { texto: "Quem se apaixonou primeiro?", opcoes: ["Eu", "Você", "A gente ao mesmo tempo"], correta: 2 },
    { texto: "Qual lugar marcou a nossa história?", opcoes: ["[LUGAR ESPECIAL]", "Uma estação de trem", "Uma praia distante"], correta: 0 },
    { texto: "Qual é uma coisa que sempre fazemos juntos?", opcoes: ["[HÁBITO DO CASAL]", "Acordar antes do sol", "Fazer trilha todo domingo"], correta: 0 },
    { texto: "Qual apelido eu mais gosto de usar com você?", opcoes: ["[APELIDO]", "Capitã", "Estrelinha"], correta: 0 },
    { texto: "O que nunca falta quando estamos juntos?", opcoes: ["[RESPOSTA DE VOCÊS]", "Um mapa aberto", "Uma receita nova"], correta: 0 },
    { texto: "Qual música lembra a gente?", opcoes: ["[NOSSA MÚSICA]", "Uma canção de viagem", "A música do primeiro filme"], correta: 0 },
    { texto: "Qual é o nosso programa simples favorito?", opcoes: ["[PROGRAMA FAVORITO]", "Organizar uma estante", "Correr na chuva"], correta: 0 },
    { texto: "O que aprendemos a fazer melhor juntos?", opcoes: ["[ALGO QUE APRENDERAM]", "Montar móveis sem manual", "Fazer malabarismo"], correta: 0 },
    { texto: "Depois de tudo, o que eu escolheria de novo?", opcoes: ["Você, sempre", "Uma viagem sem volta", "Uma sobremesa gigante"], correta: 0 },
  ],
  escolhas: [
    { pergunta: "Se pudéssemos reviver um dia…", opcoes: ["Nosso primeiro encontro", "Uma viagem", "Uma noite tranquila", "Um momento completamente aleatório"], respostas: ["Eu voltaria para sentir de novo aquele começo, agora sabendo tudo o que veio depois.", "Eu escolheria a estrada, as descobertas e você ao meu lado.", "Às vezes, o melhor dia é aquele em que o mundo fica quieto e só existe a gente.", "Os momentos sem plano acabam virando algumas das minhas histórias favoritas."] },
    { pergunta: "Se hoje fosse inteirinho nosso…", opcoes: ["Sair sem destino", "Ficar juntinhos em casa", "Repetir nosso programa favorito"], respostas: ["Com você, até não saber para onde ir parece um ótimo plano.", "Casa fica mais casa quando você está nela.", "A repetição vira tradição quando é uma coisa boa que fazemos juntos."] },
    { pergunta: "Qual lembrança merece uma moldura?", opcoes: ["Uma foto espontânea", "Uma viagem", "Uma risada que não acabava"], respostas: ["As melhores versões da gente aparecem quando esquecemos da câmera.", "Eu guardaria o lugar, mas principalmente a companhia.", "Essa lembrança já está emoldurada na minha cabeça."] },
    { pergunta: "Para a próxima aventura, você escolhe…", opcoes: ["Um lugar novo", "Um cantinho conhecido", "Deixar o acaso decidir"], respostas: ["Mal posso esperar para conhecer novos lugares pelos seus olhos.", "Há conforto em voltar aonde já fomos felizes.", "O acaso costuma acertar quando você está por perto."] },
    { pergunta: "Se nossa história tivesse uma trilha sonora…", opcoes: ["Nossa música", "Uma canção para dançar", "A playlist inteira"], respostas: ["Tem músicas que começam e, de repente, a gente está em casa.", "Eu dançaria com você mesmo sem saber os passos.", "Uma só não daria conta de tudo o que já vivemos."] },
  ],
  caracteristicas: [
    "Seu sorriso quando algo te surpreende.", "O seu jeito de contar uma história.", "A forma como você me olha.", "Seu abraço que desacelera o mundo.", "Como transforma um dia comum em memória.",
    "Sua coragem, mesmo quando sente medo.", "O cuidado que existe nos seus gestos.", "Seu jeito único de rir.", "A sua curiosidade sobre o mundo.", "Como você presta atenção nos detalhes.",
    "Sua companhia, até no silêncio.", "As pequenas manias que já são tão suas.", "O carinho que você coloca nas coisas.", "Sua força nos dias difíceis.", "A sua sinceridade.",
    "Seu jeito de fazer planos.", "A calma que encontro perto de você.", "A pessoa que você é quando ninguém está olhando.", "Como ainda me faz sentir frio na barriga.", "Tudo o que ainda vou descobrir sobre você.",
  ],
  futuro: [
    { icone: "♥", titulo: "Mais momentos juntos", mensagem: "Não precisamos saber quais serão. Só espero continuar reconhecendo você neles." },
    { icone: "✈", titulo: "Novos lugares", mensagem: "Que a gente encontre paisagens novas e continue sendo o lugar seguro um do outro." },
    { icone: "⌂", titulo: "Novas conquistas", mensagem: "Que cada vitória, grande ou pequena, tenha espaço para ser comemorada a dois." },
    { icone: "〰", titulo: "Mais histórias para contar", mensagem: "Ainda bem que a gente não sabe todas as histórias que vai contar depois." },
    { icone: "▧", titulo: "Mais memórias", mensagem: "Que nunca faltem motivos para dizer: lembra daquele dia?" },
    { icone: "✧", titulo: "O que ainda vamos descobrir", mensagem: "O futuro é aberto. E gosto de pensar nele com espaço para nós." },
  ],
  cartas: [{
    saudacao: "Meu amor,",
    paragrafos: [
      "Há dois anos, começamos a escrever uma história que eu não sabia exatamente como seria. Hoje, olhando para tudo o que vivemos, sinto gratidão por cada página e por ter encontrado em você alguém com quem dividir os dias.",
      "Você mudou a minha vida não por transformar tudo em perfeição, mas por fazer com que os momentos bons ficassem ainda mais bonitos e os difíceis fossem atravessados com mais coragem. A gente também teve dias complicados. Passamos por eles do nosso jeito, aprendendo, conversando e escolhendo continuar construindo algo que importa para nós.",
      "Eu amo as coisas grandes e as pequenas: seu sorriso, o seu jeito de falar, os nossos códigos, as risadas fora de hora e até aquelas manias que finjo não notar. Amo a pessoa que você é e a forma como posso ser eu mesmo perto de você.",
      "Obrigado por estes dois anos, por cada lembrança, por cada gesto de cuidado e por tudo o que ainda estamos descobrindo. Não sei exatamente como serão os próximos capítulos, mas sei que quero recebê-los com carinho, curiosidade e espaço para que cada um de nós continue sendo quem é.",
      "Hoje eu celebro a nossa história e, acima de tudo, a escolha de seguir ao seu lado, um dia de cada vez.",
    ],
    assinatura: "Eu escolheria você novamente.",
  }],
  mensagens: [
    "Você conhece nossa história muito bem ❤️",
    "Eu deixo passar dessa vez... porque ainda te amo mais do que ontem.",
  ],
};